### ISSUE TITLE
AjaxSpider

### ISSUE THREAD

**Issue by wurstbrot** [Grunny/zap-cli#3]
Hi,

Is there an option to use the ajax-spider with zap-cli? For example with zap2docker (like described here https://gist.github.com/Grunny/6ea8d48d711c6ad28064 )

Thank you.

**Comment by Grunny** [comment]
Not right now, but we can look to add an option that would work when the ajax-spider is available. :)

**Comment by wurstbrot** [comment]
Sure, how should we proceed? I can give advice how to talk with the ZAP API, but I am not able to write code in python.

**Comment by Grunny** [comment]
@wurstbrot Made a quick implementation here: https://github.com/Grunny/zap-cli/pull/6

You can test it out with a local install by cloning the repo, checking out the `issue-3` branch and running `pip install -e .` in a virtualenv. Let me know if that is what you're after and if there are any issues. :) I'll merge and release it so it will be available in the ZAP docker instance if there are no issues.

**Comment by Grunny** [comment]
This is released in v0.2.0 which is now available on PyPI: https://pypi.python.org/pypi/zapcli It should end up in the next docker image whenever that is updated. :)
