### ISSUE TITLE
[question] What is the command to set setOptionProxyChainName and port via ZAP-CLI

### ISSUE THREAD

**Issue by akankshasonni** [Grunny/zap-cli#35]
I'm using docker image to run the zap-cli scan and i'm behind a corporate proxy. Via ZAP GUI i'm setting the proxy from Tools->Options->Connections->Use an outgoing proxy

I'm able to do it successfully via the API too. But when I run the below command, 
docker run -u zap -p 8080 -d owasp/zap2docker-weekly zap.sh -daemon -host 127.0.0.1 -config view.OptionsUseProxyChain=true -config view.setOptionProxyChainName=10.158.100.6 -config view.setOptionProxyChainPort=8080 -config api.disablekey=true -config scanner.attackOnStart=true -config view.mode=attack -config connection.dnsTtlSuccessfulQueries=-1 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

I get the error Java Unknown Host Exception.

When I go inside the docker bash and try a curl command, it fails.

Please help.

**Comment by omerlh** [comment]
I think this issue is more related to [Zap](https://github.com/zaproxy/zaproxy) repo, as it seems like an issue with Zap. I would suggest you open a new issue there with the log output of Zap's container.
