### ISSUE TITLE
[Question] Is it possible to change the attack scan policy strength?

### ISSUE THREAD

**Issue by Lagahan** [Grunny/zap-cli#36]
As in title, when "zap-cli policies list" is run you can see that it accesses the strength of the policies, is it possible to change them at the moment through zap-cli?

Editing "Default Policy.policy" gets the desired results at the moment but it would be useful to either specify the strength through zap-cli policies enable -p "x"-s "y " or zap-cli policies "-import".

**Comment by Grunny** [comment]
Hi @Lagahan ! Sorry, for the slow response.

It is currently not possible to do this, but I just made a PR to add support for this under both the policies and scanners commands: https://github.com/Grunny/zap-cli/pull/39

This would allow you to set the strength and alert threshold for policies or individual scanners, for example:
```
# Set the attack strength Injection and Server Security policies to High
zap-cli policies set-strength -p 2,4 -s High

# Set the alert threshold for the Injection policy to High
zap-cli policies set-threshold -p 4 -t High

# Set the attack strength for the XSS scanners to Insane
zap-cli scanners set-strength --scanners xss --strength Insane

# Set the alert threshold for the External Redirect and SQL Injection scanners to High
zap-cli scanners set-threshold -s 20019,40018 -t High
```

What do you think? :)
