### ISSUE TITLE
explain relationship between `quick-scan` and `active-scan`

### ISSUE THREAD

**Issue by afeld** [Grunny/zap-cli#4]
From looking at the code, it seems like the former does everything the latter does, albeit with more options. Any reason to keep the latter around? If so, any interest in adding a bit of clarification to the README/`--help` output?

/cc @davidebest

**Comment by Grunny** [comment]
Hi! The documentation definitely needs improvement. :)

The idea of having both is flexibility when using the CLI for controlling ZAP. `active-scan` only runs an active scan against a URL that is already in ZAP's site tree, it does nothing else, and so is intended for use after other commands. Whereas `quick-scan` is intended to be a way to run quick scans with most options contained within it (including being able to start and shutdown ZAP before and after), so you can do everything in one go. Without any other options passed to the command, `quick-scan` would both open the URL to make sure it's in the site tree, run an active scan, and will always output any found alerts of the given level. So, as an example, this quick-scan command from the README:
```
zap-cli quick-scan --scanners xss,sqli --spider --recursive --exclude "some_regex_pattern" http://127.0.0.1/
```

Is equivalent to running:
```
zap-cli open-url http://127.0.0.1/
zap-cli exclude "some_regex_pattern"
zap-cli spider http://127.0.0.1/
zap-cli active-scan --scanners xss,sqli --recursive http://127.0.0.1/
zap-cli alerts
```

Does that make sense? I'll add some docs about it to the README and `--help` output and CC you on the PR for feedback. :)

**Comment by Grunny** [comment]
OK, done in https://github.com/Grunny/zap-cli/pull/5, let me know if that addresses this issue. :)
