### ISSUE TITLE
'spider' and 'active-scan' fails: Error: Missing argument "url".None

### ISSUE THREAD

**Issue by owasp-helsinki** [Grunny/zap-cli#47]
I am trying to run the OWSAP zap as part of the Jenkins pipeline. For this I have a sh script and a saved session.

Owasp zap runs inside a docker container. I have a saved session which is mounted on a folder (/onp) inside the docker container.

Steps in the script:
------------------------------------------
CONTAINER_ID=$(docker run -v /home/jenkins/workspace/api/zap/session/:/onp -u root -p 2375:2375 -d owasp/zap2docker-stable zap.sh -daemon -port 2375 -host 127.0.0.1 -config api.disablekey=true -config scanner.attackOnStart=true -config view.mode=attack -config connection.dnsTtlSuccessfulQueries=-1 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true)

docker exec $CONTAINER_ID zap-cli -p 2375 status -t 120

docker exec $CONTAINER_ID zap-cli -p 2375 -v session load /onp/onp-dev-subset-new.session

docker exec $CONTAINER_ID zap-cli -p 2375 -v spider --context-name onp 

docker exec $CONTAINER_ID zap-cli -p 2375 -v active-scan -r -c onp
---------------------------------------------

spider and active-scan fails with the following error.Console logs show this, 

[INFO]            ZAP is running
[DEBUG]           Loading session from "/onp/onp-dev-subset-new.session"
Usage: zap-cli spider [OPTIONS] URL

Error: Missing argument "url".None
Usage: zap-cli active-scan [OPTIONS] URL

Error: Missing argument "url".None
[INFO]            Issues found: 0

**Comment by Grunny** [comment]
Hi @owasp-helsinki! You should just need to provide the root URL that you're trying to scan with either active-scan or spider. For example, if a site you have saved in onp is https://example.com and that's what you want to scan, the commands should look like:

```
docker exec $CONTAINER_ID zap-cli -p 2375 -v spider --context-name onp https://example.com

docker exec $CONTAINER_ID zap-cli -p 2375 -v active-scan -r -c onp https://example.com
```

Let me know if that works for you!

**Comment by owasp-helsinki** [comment]
Thankyou so much  :-). This works...

**Comment by Grunny** [comment]
Yep, it's explained in the README [here](https://github.com/Grunny/zap-cli/blob/118fadf/README.rst#running-scans-as-authenticated-users). Once you have imported the context that has the authentication method and users configured, you simply pass the username to the spider and active-scan commands, i.e. if the user wanted to scan with was "SomeUser":
```
docker exec $CONTAINER_ID zap-cli -p 2375 -v active-scan -r -c onp -u SomeUser https://example.com
```
