### ISSUE TITLE
I can't get the alters.

### ISSUE THREAD

**Issue by purpleroc** [Grunny/zap-cli#49]
At first spider the target:  zap.spider.scan(target) 
and then scan zap.ascan.scan(target)  
and after that, when i use zap.core.alerts()  to get all results, I got a problem, some times it return 'Internal Error', and some times just can't get the result, looks like stucked.

**Comment by Grunny** [comment]
Hi, it sounds like you're having issues with the ZAP Python API client library, rather than with zap-cli. You can file an issue in the ZAP repo to report the issue there: https://github.com/zaproxy/zaproxy

**Comment by purpleroc** [comment]
ok thx
