### ISSUE TITLE
Can I run a spider attack on URLs from the loaded session?

### ISSUE THREAD

**Issue by tadsko** [Grunny/zap-cli#52]
I run an spider attack on our website then saved sessions. If i'm not mistaken, saved sessions stores the URLs that were attack previously. Is it possible to do another spider attack using the loaded saved session? How?

**Comment by Grunny** [comment]
Hi! Yep, if you load the previous session with `zap-cli session load /path/to/saved-session`, then you can simply run `zap-cli spider <URL to spider>` again. If you have a saved context, you can also pass the context name using the `--context-name` parameter, and likewise if you have a saved authentication method and users, you can pass the name of the user you would like to run the spider as using the `--user-name` parameter.

Hope that helps!

**Comment by Grunny** [comment]
Yep, you can export the context to a file, which will include the authentication method you have configured:
```
$ zap-cli context export --name ContextNameHere -f /path/to/context/file.context
```

And then it can be imported later with:
```
$ zap-cli context import /path/to/context/file.context
```

**Comment by tadsko** [comment]
Thank you, Grunny! It's working now. The other problem was the loading of saved session file. It must be on a full path 'zap-cli session load full_path/session_file'.
