### ISSUE TITLE
couldn't able to scan specific url's [Get and Post method]

### ISSUE THREAD

**Issue by idtestingking** [Grunny/zap-cli#58]
I'm using cent OS
started ZAP using below
zap-cli start
Imported context file. [ i recorded few url using zap [windows with GUI Export to context].
after that i imported into cent os non gui
using below command i imported
zap-cli context import /root/XXX/XXX.context
after that i used below command to scan it
zap-cli quick-scan -s all https://demo.com/

It is navigating to other link except the one which i gave. please help me to resolve it. i want to scan few url's using ZAP-CLI on Centos

if i where wrong please let me know alternate steps also

**Comment by Grunny** [comment]
> It is navigating to other link except the one which i gave.

Can you explain a little more what you mean by this? In your example, you're passing `https://demo.com/` as the URL to `quick-scan`, are you saying it's then scanning a different URL? Or is it scanning URLs other than those in your imported context?

If you want it to use the context for the scan, you should pass the name of the imported context to the `quick-scan` command. For example, if the context you imported was named "demo-context", your `quick-scan` command might look like this:
```
zap-cli quick-scan --context-name "demo-context" -s all https://demo.com/
```

**Comment by Grunny** [comment]
Closing for now, please reopen if you're still having the issue.
